name: Build and deploy an updated version of the website

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout virgili0/Virgilio
      uses: actions/checkout@v2
      with:
        repository: virgili0/Virgilio
        path: folder/repo
    - name: Checkout virgili0/Virgilio master
      uses: actions/checkout@v2
      with:
        repository: virgili0/Virgilio
        ref: master
        path: folder/build

    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter
        
    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Install npm dependencies
      working-directory: folder/repo/
      run: |
        cd content
        npm install
        
    - name: Vuepress build and deploy
      working-directory: folder/
      run: |
        cd repo
        find . -type f -name "*.ipynb" -exec jupyter nbconvert --to markdown {} \;
        cd content
        npm run build
        cd ..
        mkdir dist
        cp content/.vuepress/dist/* dist/ -r
        cd ..
        cp -a repo/dist/. build/
        cd build
        mkdir -m 700 ~/.ssh
        echo "${{ secrets.SSH_KEY_SECRET }}" > ~/.ssh/id_ed25519
        chmod 0600 ~/.ssh/id_ed25519
        git config --local user.name "GitHub Action"
        git config --global user.email "virgilio.datascience@gmail.com"
        git add .
        git commit -m "Update build" && git push || :
